lukebushur/Research-Web-Portal

client/src/app/demoProjects/demoProject.component.css
client/src/app/demoProjects/demoProject.component.html
client/src/app/signout/signout.component.css
client/src/app/signup/signup.component.ts
documentation/docker-deployment-diagram.plantuml
server/helpers/inputValidation/validation.js

- Updated docker diagram to be less technical
- Server validation for email - max is 254
- Signup page validation - email is up to 254 characters
- Signout page text is centered
- demoProjects text telling users table is scrollable, cannot apply button does not overflow

Final touches to project

---

documentation/database-class-diagram.puml

adds in the class diagram uml to documentation/

Add in database class diagram to main

---

client/src/app/app-routing.module.ts
client/src/app/app.module.ts
client/src/app/components/post_creation/catergory-field/catergory-field.component.ts
client/src/app/components/post_creation/custom-field-modal/modal.component.ts
client/src/app/components/post_creation/custom-question/custom-question.component.html
client/src/app/components/post_creation/custom-question/custom-question.component.spec.ts
client/src/app/components/post_creation/custom-question/custom-question.component.ts
client/src/app/components/post_creation/posts.component.html
client/src/app/components/post_creation/posts.component.spec.ts
client/src/app/components/post_creation/posts.component.ts
client/src/app/components/research-project-card/research-project-card.component.css
client/src/app/components/research-project-card/research-project-card.component.html

This PR has an unstyled but fully functional post-creation page. This allows for faculty to create posts about their research projects with different question types, i.e., text responses, checkboxes, and radio buttons. It additionally has the code needed to make a successful project creation request through the front end.

Post creation

---

client/package-lock.json
client/src/app/_helpers/auth/app.security.ts
client/src/app/_helpers/auth/auth-guard/auth.guard.spec.ts
client/src/app/_helpers/auth/auth-guard/auth.guard.ts
client/src/app/app-routing.module.ts
client/src/app/app.module.ts
client/src/app/components/apply-to-post/apply-to-post.component.html
client/src/app/components/auto-sign-up-component/auto-sign-up-component.component.spec.ts
client/src/app/components/confirmemail/email.component.ts
client/src/app/components/industry-dashboard/industry-dashboard.component.html
client/src/app/components/industry-dashboard/industry-dashboard.component.spec.ts
client/src/app/components/industry-dashboard/industry-dashboard.component.ts
client/src/app/components/login/login.component.css
client/src/app/components/login/login.component.html
client/src/app/components/login/login.component.ts
client/src/app/components/post_creation/posts.component.ts
client/src/app/components/signup/signup.component.html
client/src/app/components/signup/signup.component.ts
client/src/controllers/industry-dashboard-controller/industry-dashboard.service.spec.ts
client/src/controllers/industry-dashboard-controller/industry-dashboard.service.ts
client/src/controllers/login-controller/login.service.ts
client/src/controllers/signout-controller/signout.service.ts
client/src/controllers/signup-controller/signup.service.ts
client/src/environments/environment.development.ts
client/src/environments/environment.ts
client/tsconfig.json
server/controllers/authenticate.js
server/controllers/industry.js
server/routes/industry.js
server/server.js

- Created basic industry dashboard component
- Created industry user routes and controllers files in the server
- Upon signing up or logging into an industry account, the server sends the accountType, and the front-end can use this to direct the user to a component associated with their accountType
- Updated the login and signup components to use reactive forms, which are supposed to be faster and more scalable
- Added form validation to the login component
- Added comments to the login and registration components
- Updated dependencies to eliminate security vulnerabilities on the front-end
- Enabled the Angular compiler's strict mode, which performs more, comprehensive template type-checking
- Formatted several files
- Removed unused imports in several files

Refactoring & Industry User Registration & Login

---

client/src/app/components/applied-student-table/applied-student-table.component.html
client/src/app/components/applied-student-table/applied-student-table.component.ts
client/src/app/components/research-project-card/research-project-card.component.ts
client/src/app/components/view-project/view-project.component.html
client/src/app/components/view-project/view-project.component.ts
client/src/app/controllers/faculty-project-controller/faculty-project.service.ts
server/controllers/facultyProjects.js
server/models/application.js
server/models/project.js

Small changes to the previously created viewProject page. It now has sorting tables and is ready for nick to modify and add filtering and searching to.

Bare Minimum for the view faculty page added

---

client/src/app/components/login/login.component.spec.ts
client/src/app/components/login/login.component.ts

This pr fixes the error of sign in routing to the faculty dashboard when using a student account.

Fixed sign in routing error

---

client/src/app/components/confirm-reset-password/confirm-reset-password.component.css
client/src/app/components/confirm-reset-password/confirm-reset-password.component.html
client/src/app/components/confirm-reset-password/confirm-reset-password.component.spec.ts
client/src/app/components/confirm-reset-password/confirm-reset-password.component.ts
client/src/app/components/forgot-password/forgot-password.component.html
client/src/app/components/forgot-password/forgot-password.component.spec.ts
client/src/app/components/forgot-password/forgot-password.component.ts
client/src/app/controllers/login-controller/login.service.ts

- Moved the new password field from the initial forgot password page to the confirm reset password page.
- Updated unit tests accordingly

Security Fix for Forgot Password

---

client/src/app/app-routing.module.ts
client/src/app/components/edit-profile-screen/edit-profile-screen.component.css
client/src/app/components/edit-profile-screen/edit-profile-screen.component.html
client/src/app/components/edit-profile-screen/edit-profile-screen.component.ts
client/src/app/components/student-view-application/student-view-application.component.css
client/src/app/components/student-view-application/student-view-application.component.html
server/controllers/accountManagment.js
server/unitTests/applications.test.js

- Fixed update account route on back-end not updating GPA and majors
- Several styling changes for edit profile and student view application

Styling and Functionality Fixes

---

client/src/app/_helpers/auth/role-guard/role.guard.ts
client/src/app/app-routing.module.ts
client/src/app/components/apply-to-post/apply-to-post.component.spec.ts
client/src/app/components/apply-to-post/apply-to-post.component.ts
client/src/app/components/login/login.component.spec.ts
client/src/app/components/login/login.component.ts
client/src/app/components/research-project-card/research-project-card.component.html
client/src/app/components/signup/signup.component.spec.ts
client/src/app/components/signup/signup.component.ts
client/src/app/components/student-applications-overview/student-applications-overview.component.html
client/src/app/components/student-applications-overview/student-applications-overview.component.ts
client/src/app/components/student-dashboard/dashboard.component.css
client/src/app/components/student-dashboard/dashboard.component.html
client/src/app/components/student-dashboard/dashboard.component.ts
client/src/app/components/student-opportunites-search-page/student-opportunites-search-page.component.ts
client/src/app/components/student-toolbar/student-toolbar.component.css
client/src/app/components/student-toolbar/student-toolbar.component.html
client/src/app/components/student-toolbar/student-toolbar.component.spec.ts
client/src/app/components/student-toolbar/student-toolbar.component.ts
client/src/app/components/student-view-application/student-view-application.component.css
client/src/app/components/student-view-application/student-view-application.component.html
client/src/app/components/student-view-application/student-view-application.component.ts

- Created responsive student toolbar and side navigation component `StudentToolbarComponent` using Material UI
- Added unit tests
- Made `StudentToolbarComponent` the root student route, and every other student route appears within the content of this component
- Renamed student routes for consistency and understandability
- Removed erroneous routes
- Updated all links involving student routes affected by the nested routing implementation
- Fixed apply-to-post not working due to professor email and project ID not being included in server request
- Fixed rescind application button on view application page not working due to misnamed variable
- Fixed view application page not displaying radio button question responses correctly due to all radio buttons being in one group
- Fixed styling …

Student Toolbar & Side Navigation, Plus Other Fixes

---

client/src/app/components/view-application/view-application.component.ts
db-seeder/.env_example
db-seeder/Seeder.py

This fixes answers not being displayed on the view-application pages

Fix answer generation not displaying on site

---

client/src/app/components/post_creation/posts.component.html

changed to raised button on create project page

changed to mat raised button

---

client/src/app/_helpers/auth/auth-guard/auth.guard.spec.ts
client/src/app/_helpers/auth/auth-guard/auth.guard.ts
client/src/app/_helpers/auth/interceptor/token-interceptor.service.spec.ts
client/src/app/components/faculty-dashboard/faculty-dashboard.component.spec.ts
client/src/app/components/research-project-card/research-project-card.component.spec.ts
client/src/app/components/research-project-card/research-project-card.component.ts
client/src/app/components/student-dashboard/dashboard.component.html
client/src/app/components/student-opportunites-search-page/student-opportunites-search-page.component.html
client/src/app/controllers/email-controller/email.service.ts
client/src/app/controllers/faculty-project-controller/faculty-project.service.spec.ts
client/src/app/controllers/faculty-project-controller/faculty-project.service.ts

See the commit messages for a full description of what I did.

Testing and Other Changes

---

client/src/app/components/apply-to-post/apply-to-post.component.html
client/src/app/components/edit-profile-screen/edit-profile-screen.component.ts
client/src/app/components/research-project-card/research-project-card.component.html
client/src/app/components/research-project-card/research-project-card.component.ts
client/src/app/components/student-dashboard/dashboard.component.css
client/src/app/components/student-dashboard/dashboard.component.html
client/src/app/components/student-dashboard/dashboard.component.spec.ts
client/src/app/components/student-dashboard/dashboard.component.ts
client/src/app/components/student-opportunites-search-page/student-opportunites-search-page.component.html
client/src/app/components/student-opportunites-search-page/student-opportunites-search-page.component.spec.ts
client/src/app/components/student-opportunites-search-page/student-opportunites-search-page.component.ts

Adds in multiple bug fixes & general improvements to the client side, see commits for more details.

Nicks sprint 11 tasks

---

client/src/app/components/signup/signup.component.css
client/src/app/components/signup/signup.component.html
client/src/app/components/signup/signup.component.ts

the register page has text button that routes to login

routing button made

---

client/src/app/app.component.html
client/src/app/app.component.spec.ts
client/src/app/app.component.ts
client/src/app/app.config.ts
client/src/app/app.routes.ts
client/src/app/components/student-opportunites-search-page/student-opportunites-search-page.component.css
client/src/app/components/student-opportunites-search-page/student-opportunites-search-page.component.html
client/src/app/components/student-opportunites-search-page/student-opportunites-search-page.component.ts
client/src/app/controllers/faculty-project-controller/faculty-project.service.spec.ts
client/src/app/controllers/faculty-project-controller/faculty-project.service.ts
client/src/app/controllers/load-controller/loader.service.ts
client/src/app/controllers/profile-controller/profile-service.service.spec.ts
client/src/app/controllers/profile-controller/profile-service.service.ts
client/src/app/controllers/signout-controller/signout.service.spec.ts
client/src/app/controllers/signout-controller/signout.service.ts
client/src/app/loading.interceptor.spec.ts
client/src/app/loading.interceptor.ts
client/src/index.html

- Added comments to services & components
- Removed unnecessary title variable from AppComponent
- Added back search button to search page, made bar longer

Comments & Small Changes

---

client/src/app/app.routes.ts
client/src/app/components/applied-student-table/applied-student-table.component.spec.ts
client/src/app/components/edit-profile-screen/edit-profile-screen.component.css
client/src/app/components/edit-profile-screen/edit-profile-screen.component.html
client/src/app/components/edit-profile-screen/edit-profile-screen.component.spec.ts
client/src/app/components/edit-profile-screen/edit-profile-screen.component.ts
client/src/app/components/faculty-dashboard/faculty-dashboard.component.css
client/src/app/components/faculty-toolbar/faculty-toolbar.component.html
client/src/app/components/login/login.component.spec.ts
client/src/app/components/login/login.component.ts
client/src/app/components/signup/signup.component.html
client/src/app/components/signup/signup.component.spec.ts
client/src/app/components/signup/signup.component.ts
client/src/app/components/student-toolbar/student-toolbar.component.html
server/helpers/inputValidation/accountValidation.js

See commit messages for a full summary of changes.

Edit Profile and Other Component Fixes/Improvements

---

client/src/app/components/view-application/view-application.component.css
client/src/app/components/view-application/view-application.component.html

changed color to orange added space to buttons

---

aws/buildspec.yaml

Created buildspec.yaml file for AWS CodeBuild

Created Buildspec

---

client/src/app/auth/confirm-reset-password/confirm-reset-password.component.css
client/src/app/auth/forgot-password/forgot-password.component.css
client/src/app/auth/login/login.component.css
client/src/app/auth/signup/signup.component.css

Fixed by removing absolute positioning and using `margin: 70px auto;` to center content toward the top

Fixed pages that used absolute positioning being offscreen

---

aws/dev/backend-dev-task-definition-template.json
aws/dev/buildspec.yaml
aws/dev/frontend-dev-task-definition-template.json

Created task definitions and buildspec for developer deployment

Dev AWS Deployment

---

client/src/app/core/edit-profile-screen/edit-profile-screen.component.ts
client/src/app/core/loading-interceptor/loading.interceptor.ts
client/src/app/faculty/applied-student-table/applied-student-table.component.spec.ts

Implemented changes from last semester not already in the main branch
- Added comments to `EditProfileScreenComponent`
- Added comments to `loadingInterceptor`
- Added test case to `AppliedStudentTableComponent` to test accepting a student from the table

Leftover Changes

---

client/package-lock.json
client/src/app/app.routes.ts
client/src/app/core/landing/landing.component.css
client/src/app/core/landing/landing.component.html
client/src/app/core/landing/landing.component.spec.ts
client/src/app/core/landing/landing.component.ts

- Created a landing page to inform visitors how to get started
- Located at root route (`/`)
- Links to sign up page and login page
- Added license to package-lock.json

Landing Page

---

client/src/app/app.routes.ts
client/src/app/auth/signup/signup.component.html
client/src/app/auth/signup/signup.component.spec.ts
client/src/app/auth/signup/signup.component.ts
client/src/app/auth/terms-of-service/terms-of-service.component.css
client/src/app/auth/terms-of-service/terms-of-service.component.html
client/src/app/auth/terms-of-service/terms-of-service.component.spec.ts
client/src/app/auth/terms-of-service/terms-of-service.component.ts
client/src/app/faculty/faculty-dashboard/faculty-dashboard.component.ts
client/src/app/faculty/research-project-card/research-project-card.component.html
client/src/app/faculty/research-project-card/research-project-card.component.ts

Added terms of service screen that users must accept to sign up
Added publish draft project functionality

Additional Fixes
